name: fastapi app test

on:
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        defaults: 
            run:
                working-directory: ./app/

        strategy:
            matrix:
                pythin-version: [3.8.5]
        
        env:
            MODE: "dev"
        
        steps:
            - uses: actions/checkout@v3

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.pythin-version }}
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip 
                pip install -r ../requirements.txt
                
            - name: Test app code
              run: python ./main_test.py

